name: weatherly
description: "Production-ready Flutter weather app with forecasts, radar, and alerts."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3
  
  # Networking
  dio: ^5.4.3+1
  retrofit: 4.6.0
  
  # JSON & Models
  freezed_annotation: ^3.1.0
  json_annotation: ^4.8.1
  
  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.3
  
  # Location
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  
  # Maps
  flutter_map: ^7.0.0
  latlong2: ^0.9.1
  
  # Charts
  fl_chart: ^1.1.1
  
  # Animations
  lottie: ^3.1.2
  
  # Notifications
  flutter_local_notifications: ^19.5.0
  
  # UI
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10
  
  # Utilities
  flutter_dotenv: ^6.0.0
  equatable: ^2.0.5
  path_provider: ^2.1.3
  share_plus: ^12.0.1
  permission_handler: ^12.0.1
  connectivity_plus: ^7.0.0
  http: ^1.2.1
  google_fonts: ^6.3.2
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^6.0.0
  
  # Code Generation
  build_runner: ^2.4.9
  freezed: ^3.2.3
  json_serializable: ^6.8.0
  retrofit_generator: ^10.0.0
  riverpod_generator: ^3.0.3
  
  # Testing
  mocktail: ^1.0.3
  integration_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icons/icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  
  assets:
    - assets/animations/
    - assets/images/
    - assets/images/icons/
    - assets/weather icons/fill/all/
    - assets/weather icons/line/all/
    - .env
  
  generate: true
